/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.dsoo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author ASUS
 */
public class JFmenuprincipal extends javax.swing.JFrame {
    
    
    String tempid;
    /**
     * Creates new form JFmenuprincipal
     */
    public JFmenuprincipal() {
        initComponents();
        pnlTableDent.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDent = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblNomApli = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnMax = new javax.swing.JButton();
        pnlTableDent = new javax.swing.JPanel();
        lblNomTablaDent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataDent = new javax.swing.JTable();
        btnNewDent = new javax.swing.JButton();
        btnDelDent = new javax.swing.JButton();
        btnModDent = new javax.swing.JButton();
        btnSearchDent = new javax.swing.JButton();
        PnlTxtsDent = new javax.swing.JPanel();
        lblDent = new javax.swing.JLabel();
        txtNomDent = new javax.swing.JTextField();
        txtApelDent = new javax.swing.JTextField();
        txtEspecDent = new javax.swing.JTextField();
        txtTelDent = new javax.swing.JTextField();
        txtCelDent = new javax.swing.JTextField();
        txtDiasDent = new javax.swing.JTextField();
        lblDiasDent = new javax.swing.JLabel();
        lblCelDent = new javax.swing.JLabel();
        lblTelDent = new javax.swing.JLabel();
        lblEspecDent = new javax.swing.JLabel();
        lblApellDent = new javax.swing.JLabel();
        lblNomDent = new javax.swing.JLabel();
        btnInsertDent = new javax.swing.JButton();
        PnlTxtsDentDel = new javax.swing.JPanel();
        lblDentDel = new javax.swing.JLabel();
        lblIDDent1 = new javax.swing.JLabel();
        btnDelDentConfirm = new javax.swing.JButton();
        lblDentDel1 = new javax.swing.JLabel();
        lblDentDelNom = new javax.swing.JLabel();
        pnlTablePac = new javax.swing.JPanel();
        lblNomTablaPac = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataPac = new javax.swing.JTable();
        btnNewPac = new javax.swing.JButton();
        btnDelPac = new javax.swing.JButton();
        btnModPac = new javax.swing.JButton();
        btnSearchPac = new javax.swing.JButton();
        PnlTxtsPac = new javax.swing.JPanel();
        lblPac = new javax.swing.JLabel();
        txtNomPac = new javax.swing.JTextField();
        txtApelPac = new javax.swing.JTextField();
        txtEdadPac = new javax.swing.JTextField();
        lblEspecPac = new javax.swing.JLabel();
        lblApellPac = new javax.swing.JLabel();
        lblNomPac = new javax.swing.JLabel();
        btnInsertPac = new javax.swing.JButton();
        PnlTxtsPacDel = new javax.swing.JPanel();
        lblPacDel = new javax.swing.JLabel();
        lblIDPacDel = new javax.swing.JLabel();
        btnDelPacConfirm = new javax.swing.JButton();
        lblDentDel3 = new javax.swing.JLabel();
        lblPacDelNom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("JFmenu"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("LOGO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnDent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDent.setText("DENTISTAS");
        btnDent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDentActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("PACIENTES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("CITAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("PAGOS");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("INVENTARIO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("USUARIOS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDent, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnDent, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblNomApli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNomApli.setText("Nombre de la aplicación");

        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMin.setText("-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnMax.setText("..");
        btnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(lblNomApli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMax)
                .addGap(5, 5, 5)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNomApli))
                    .addComponent(btnMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        lblNomTablaDent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomTablaDent.setText("Tabla Dentista");

        tableDataDent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Especialidad", "telefono", "Celular", "Dias que viene"
            }
        ));
        tableDataDent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataDentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataDent);

        btnNewDent.setText("Nuevo");
        btnNewDent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDentActionPerformed(evt);
            }
        });

        btnDelDent.setText("Eliminar");
        btnDelDent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDentActionPerformed(evt);
            }
        });

        btnModDent.setText("Modificar");
        btnModDent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModDentActionPerformed(evt);
            }
        });

        btnSearchDent.setText("Buscar");

        lblDent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDent.setText("Nuevo Dentista");

        txtNomDent.setText("-");

        txtApelDent.setText("-");

        txtEspecDent.setText("-");

        txtTelDent.setText("-");

        txtCelDent.setText("-");

        txtDiasDent.setText("-");

        lblDiasDent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDiasDent.setText("Dias que viene:");

        lblCelDent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCelDent.setText("Celular:");

        lblTelDent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelDent.setText("Telefono:");

        lblEspecDent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEspecDent.setText("Especialidad:");

        lblApellDent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblApellDent.setText("Apellidos:");

        lblNomDent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNomDent.setText("Nombre:");

        btnInsertDent.setText("Insertar");
        btnInsertDent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertDentMouseExited(evt);
            }
        });
        btnInsertDent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertDentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlTxtsDentLayout = new javax.swing.GroupLayout(PnlTxtsDent);
        PnlTxtsDent.setLayout(PnlTxtsDentLayout);
        PnlTxtsDentLayout.setHorizontalGroup(
            PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblDent))
                    .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                                .addComponent(lblDiasDent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiasDent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlTxtsDentLayout.createSequentialGroup()
                                    .addComponent(lblCelDent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCelDent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                                    .addComponent(lblTelDent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelDent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                                    .addComponent(lblEspecDent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                    .addComponent(txtEspecDent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                                    .addComponent(lblApellDent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtApelDent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                                    .addComponent(lblNomDent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNomDent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnInsertDent)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PnlTxtsDentLayout.setVerticalGroup(
            PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsDentLayout.createSequentialGroup()
                .addComponent(lblDent)
                .addGap(29, 29, 29)
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomDent)
                    .addComponent(txtNomDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellDent)
                    .addComponent(txtApelDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecDent)
                    .addComponent(txtEspecDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelDent)
                    .addComponent(txtTelDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCelDent)
                    .addComponent(txtCelDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasDent)
                    .addComponent(txtDiasDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInsertDent)
                .addContainerGap())
        );

        lblDentDel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDentDel.setText("Eliminar Dentista");

        lblIDDent1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnDelDentConfirm.setText("Insertar");
        btnDelDentConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDentConfirmActionPerformed(evt);
            }
        });

        lblDentDel1.setText("Seguro que quieres eliminar el dentista: ");

        lblDentDelNom.setText("-:-");

        javax.swing.GroupLayout PnlTxtsDentDelLayout = new javax.swing.GroupLayout(PnlTxtsDentDel);
        PnlTxtsDentDel.setLayout(PnlTxtsDentDelLayout);
        PnlTxtsDentDelLayout.setHorizontalGroup(
            PnlTxtsDentDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                .addGroup(PnlTxtsDentDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblDentDel))
                    .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIDDent1)
                        .addGroup(PnlTxtsDentDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlTxtsDentDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDentDel1)
                                    .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(lblDentDelNom))))
                            .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnDelDentConfirm)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PnlTxtsDentDelLayout.setVerticalGroup(
            PnlTxtsDentDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsDentDelLayout.createSequentialGroup()
                .addComponent(lblDentDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDentDel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDentDelNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelDentConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIDDent1))
        );

        javax.swing.GroupLayout pnlTableDentLayout = new javax.swing.GroupLayout(pnlTableDent);
        pnlTableDent.setLayout(pnlTableDentLayout);
        pnlTableDentLayout.setHorizontalGroup(
            pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableDentLayout.createSequentialGroup()
                .addGroup(pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableDentLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableDentLayout.createSequentialGroup()
                        .addGroup(pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableDentLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnNewDent, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelDent, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModDent, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchDent, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTableDentLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(lblNomTablaDent)))
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PnlTxtsDentDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlTxtsDent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlTableDentLayout.setVerticalGroup(
            pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableDentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNomTablaDent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableDentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTableDentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewDent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelDent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModDent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchDent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTableDentLayout.createSequentialGroup()
                        .addComponent(PnlTxtsDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnlTxtsDentDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        lblNomTablaPac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomTablaPac.setText("Tabla Paciente");

        tableDataPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Especialidad", "telefono", "Celular", "Dias que viene"
            }
        ));
        tableDataPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataPacMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDataPac);

        btnNewPac.setText("Nuevo");
        btnNewPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPacActionPerformed(evt);
            }
        });

        btnDelPac.setText("Eliminar");
        btnDelPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPacActionPerformed(evt);
            }
        });

        btnModPac.setText("Modificar");
        btnModPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPacActionPerformed(evt);
            }
        });

        btnSearchPac.setText("Buscar");

        lblPac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPac.setText("Nuevo Paciente");

        txtNomPac.setText("-");

        txtApelPac.setText("-");

        txtEdadPac.setText("-");

        lblEspecPac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEspecPac.setText("Edad:");

        lblApellPac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblApellPac.setText("Apellidos:");

        lblNomPac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNomPac.setText("Nombre:");

        btnInsertPac.setText("Insertar");
        btnInsertPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertPacMouseExited(evt);
            }
        });
        btnInsertPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlTxtsPacLayout = new javax.swing.GroupLayout(PnlTxtsPac);
        PnlTxtsPac.setLayout(PnlTxtsPacLayout);
        PnlTxtsPacLayout.setHorizontalGroup(
            PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                .addGroup(PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblPac))
                    .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                                .addComponent(lblApellPac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(txtApelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                                .addComponent(lblNomPac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomPac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                                .addComponent(lblEspecPac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInsertPac)
                                    .addComponent(txtEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        PnlTxtsPacLayout.setVerticalGroup(
            PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsPacLayout.createSequentialGroup()
                .addComponent(lblPac)
                .addGap(29, 29, 29)
                .addGroup(PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomPac)
                    .addComponent(txtNomPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellPac)
                    .addComponent(txtApelPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTxtsPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecPac)
                    .addComponent(txtEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertPac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPacDel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPacDel.setText("Eliminar Paciente");

        lblIDPacDel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnDelPacConfirm.setText("Eliminar");
        btnDelPacConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPacConfirmActionPerformed(evt);
            }
        });

        lblDentDel3.setText("Seguro que quieres eliminar el dentista: ");

        lblPacDelNom.setText("-:-");

        javax.swing.GroupLayout PnlTxtsPacDelLayout = new javax.swing.GroupLayout(PnlTxtsPacDel);
        PnlTxtsPacDel.setLayout(PnlTxtsPacDelLayout);
        PnlTxtsPacDelLayout.setHorizontalGroup(
            PnlTxtsPacDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                .addGroup(PnlTxtsPacDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblPacDel))
                    .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIDPacDel)
                        .addGroup(PnlTxtsPacDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlTxtsPacDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDentDel3)
                                    .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(lblPacDelNom))))
                            .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnDelPacConfirm)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PnlTxtsPacDelLayout.setVerticalGroup(
            PnlTxtsPacDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTxtsPacDelLayout.createSequentialGroup()
                .addComponent(lblPacDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDentDel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPacDelNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelPacConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIDPacDel))
        );

        javax.swing.GroupLayout pnlTablePacLayout = new javax.swing.GroupLayout(pnlTablePac);
        pnlTablePac.setLayout(pnlTablePacLayout);
        pnlTablePacLayout.setHorizontalGroup(
            pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablePacLayout.createSequentialGroup()
                .addGroup(pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablePacLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTablePacLayout.createSequentialGroup()
                        .addGroup(pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTablePacLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnNewPac, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModPac, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchPac, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTablePacLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(lblNomTablaPac)))
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PnlTxtsPacDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlTxtsPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlTablePacLayout.setVerticalGroup(
            pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablePacLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNomTablaPac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablePacLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTablePacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewPac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModPac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchPac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTablePacLayout.createSequentialGroup()
                        .addComponent(PnlTxtsPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnlTxtsPacDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnlTableDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(250, Short.MAX_VALUE)
                    .addComponent(pnlTablePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTableDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .addComponent(pnlTablePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDentActionPerformed
        // TODO add your handling code here:
        pnlTableDent.setVisible(true);
        actualizarTablaDent();
        PnlTxtsDent.setVisible(false);
        PnlTxtsDentDel.setVisible(false);
    }//GEN-LAST:event_btnDentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaxActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnNewDentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDentActionPerformed
        // TODO add your handling code here:
        lblDent.setText("Nuevo Dentista");
        btnInsertDent.setText("Insertar");
        PnlTxtsDent.setVisible(true);
    }//GEN-LAST:event_btnNewDentActionPerformed

    private void btnDelDentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDentActionPerformed
        // TODO add your handling code here:
        ActualDent = filadentista();
        lblDentDelNom.setText(ActualDent.getNombre());
        PnlTxtsDentDel.setVisible(true);
    }//GEN-LAST:event_btnDelDentActionPerformed

    private void btnInsertDentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertDentMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertDentMouseExited

    private void btnInsertDentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertDentActionPerformed
        // TODO add your handling code here:
        if(btnInsertDent.getText().equals("Insertar")){
            agregarTablaDent();
        }else{
            modificarTablaDent();
        }
        
    }//GEN-LAST:event_btnInsertDentActionPerformed

    private void btnDelDentConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDentConfirmActionPerformed
        // TODO add your handling code here:
        eliminarTablaDent();
    }//GEN-LAST:event_btnDelDentConfirmActionPerformed

    private void tableDataDentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataDentMouseClicked
        // TODO add your handling code here:
        PnlTxtsDent.setVisible(false);
        PnlTxtsDentDel.setVisible(false);
    }//GEN-LAST:event_tableDataDentMouseClicked

    private void btnModDentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModDentActionPerformed
        // TODO add your handling code here:
        ActualDent = filadentista();
        lblDent.setText("Modificar Dentista");
        btnInsertDent.setText("Modficar");
        tempid = ActualDent.getId();
        txtNomDent.setText(ActualDent.getNombre());
        txtApelDent.setText(ActualDent.getApellido());
        txtEspecDent.setText(ActualDent.getEspecialidad());
        txtTelDent.setText(Integer.toString(ActualDent.getTelefono()));
        txtCelDent.setText(Integer.toString(ActualDent.getCelular()));
        txtDiasDent.setText(ActualDent.getDias());
        PnlTxtsDent.setVisible(true);
    }//GEN-LAST:event_btnModDentActionPerformed

    private void tableDataPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataPacMouseClicked
        // TODO add your handling code here:
        PnlTxtsPac.setVisible(false);
        PnlTxtsPacDel.setVisible(false);
    }//GEN-LAST:event_tableDataPacMouseClicked

    private void btnNewPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPacActionPerformed
        // TODO add your handling code here:
        lblPac.setText("Nuevo Paciente");
        btnInsertPac.setText("Insertar");
        PnlTxtsPac.setVisible(true);
    }//GEN-LAST:event_btnNewPacActionPerformed

    private void btnDelPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelPacActionPerformed

    private void btnModPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModPacActionPerformed

    private void btnInsertPacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertPacMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertPacMouseExited

    private void btnInsertPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertPacActionPerformed

    private void btnDelPacConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPacConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelPacConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Funciones de la ventana
    
    //Valores de función
    private Dentista ActualDent;
    private Pacientes ActualPac;
    
    
    //Funciones de Dentista
    private void agregarTablaDent(){
        Dentista Dent = new Dentista();
        Dent.setNombre(txtNomDent.getText());
        Dent.setApellido(txtApelDent.getText());
        Dent.setEspecialidad(txtEspecDent.getText());
        Dent.setCelular(Integer.parseInt(txtCelDent.getText()));
        Dent.setTelefono(Integer.parseInt(txtTelDent.getText()));
        Dent.setDias(txtDiasDent.getText());
        if(Dent.agregar()){
            actualizarTablaDent();
            txtNomDent.setText("-:-");
            txtApelDent.setText("-:-");
            txtEspecDent.setText("-:-");
            txtTelDent.setText("-:-"); 
            txtCelDent.setText("-:-"); 
            txtDiasDent.setText("-:-");
            PnlTxtsDent.setVisible(false);
        }else{
            System.out.println("Error en SQL");
        }
    }
    private Dentista filadentista(){
        Dentista Dent = new Dentista();
        int Tcol = tableDataDent.getSelectedRow();
        Dent.setId(String.valueOf(tableDataDent.getValueAt(Tcol, 0)));
        Dent.setNombre(String.valueOf(tableDataDent.getValueAt(Tcol, 1)));
        Dent.setApellido(String.valueOf(tableDataDent.getValueAt(Tcol, 2)));
        Dent.setEspecialidad(String.valueOf(tableDataDent.getValueAt(Tcol, 3)));
        Dent.setCelular(Integer.parseInt(String.valueOf(tableDataDent.getValueAt(Tcol, 4))));
        Dent.setTelefono(Integer.parseInt(String.valueOf(tableDataDent.getValueAt(Tcol, 5))));
        Dent.setDias(String.valueOf(tableDataDent.getValueAt(Tcol, 6)));
        System.out.println(Dent.getId() + Dent.getNombre() + Dent.getApellido() + Dent.getEspecialidad() + Dent.getCelular() + Dent.getTelefono() + Dent.getDias());
        return Dent;
    }
    private boolean eliminarTablaDent(){
        ActualDent.eliminar();
        PnlTxtsDentDel.setVisible(false);
        actualizarTablaDent();
        return true;
    }
    private void modificarTablaDent(){
        Dentista Dent = new Dentista();
        Dent.setId(tempid);
        Dent.setNombre(txtNomDent.getText());
        Dent.setApellido(txtApelDent.getText());
        Dent.setEspecialidad(txtEspecDent.getText());
        Dent.setCelular(Integer.parseInt(txtCelDent.getText()));
        Dent.setTelefono(Integer.parseInt(txtTelDent.getText()));
        Dent.setDias(txtDiasDent.getText());
        if(Dent.modificar()){
            actualizarTablaDent();
            txtNomDent.setText("-:-");
            txtApelDent.setText("-:-");
            txtEspecDent.setText("-:-");
            txtTelDent.setText("-:-"); 
            txtCelDent.setText("-:-"); 
            txtDiasDent.setText("-:-");
            btnInsertDent.setText("Insertar");
            lblDent.setText("Nuevo Dentista");
            PnlTxtsDent.setVisible(false);
        }else{
            System.out.println("Error en SQL");
        }
    }
    private void actualizarTablaDent(){
        Dentista Dent = new Dentista();
        ArrayList<Dentista> Select = Dent.getDentistas();
        DefaultTableModel Temp = new DefaultTableModel();
        Temp.addColumn("ID");
        Temp.addColumn("Nombre");
        Temp.addColumn("Apellidos");
        Temp.addColumn("Especialidad");
        Temp.addColumn("Telefono");
        Temp.addColumn("Celular");
        Temp.addColumn("Dias");
        for(int i = 0; i  < Select.size(); i++){
            Temp.addRow(Dent.RowDent(Select.get(i)));
        }
        tableDataDent.setModel(Temp);
    }
    
    
    //Funciones de Paciente
    private void agregarTablaPac(){
        Pacientes Pac = new Pacientes();
        Pac.setNombre(txtNomPac.getText());
        Pac.setApellidos(txtApelPac.getText());
        Pac.setEdad(txtEdadPac.getText());
        if(Pac.agregar()){
            actualizarTablaPac();
            txtNomPac.setText("-:-");
            txtApelPac.setText("-:-");
            txtEdadPac.setText("-:-");
            PnlTxtsPac.setVisible(false);
        }else{
            System.out.println("Error en SQL");
        }
    }
    private Pacientes filapaciente(){
        Pacientes Pac = new Pacientes();
        int Tcol = tableDataPac.getSelectedRow();
        Pac.setId(String.valueOf(tableDataPac.getValueAt(Tcol, 0)));
        Pac.setNombre(String.valueOf(tableDataPac.getValueAt(Tcol, 1)));
        Pac.setApellidos(String.valueOf(tableDataPac.getValueAt(Tcol, 2)));
        Pac.setEdad(String.valueOf(tableDataPac.getValueAt(Tcol, 3)));
        System.out.println(Pac.getId() + Pac.getNombre() + Pac.getApellidos() + Pac.getEdad());
        return Pac;
    }
    private boolean eliminarTablaPac(){
        ActualPac.eliminar();
        PnlTxtsPacDel.setVisible(false);
        actualizarTablaPac();
        return true;
    }
    private void modificarTablaPac(){
        Pacientes Pac = new Pacientes();
        Pac.setId(tempid);
        Pac.setNombre(txtNomPac.getText());
        Pac.setApellidos(txtApelPac.getText());
        Pac.setEdad(txtEdadPac.getText());
        if(Pac.modificar()){
            actualizarTablaPac();
            txtNomPac.setText("-:-");
            txtApelPac.setText("-:-");
            txtEdadPac.setText("-:-");
            btnInsertPac.setText("Insertar");
            lblPac.setText("Nuevo Dentista");
            PnlTxtsPac.setVisible(false);
        }else{
            System.out.println("Error en SQL");
        }
    }
    private void actualizarTablaPac(){
        Pacientes pac = new Pacientes();
        ArrayList<Pacientes> Select = pac.getPacientes();
        DefaultTableModel Temp = new DefaultTableModel();
        Temp.addColumn("ID");
        Temp.addColumn("Nombre");
        Temp.addColumn("Apellidos");
        Temp.addColumn("Edad");
        for(int i = 0; i  < Select.size(); i++){
            Temp.addRow(pac.RowDent(Select.get(i)));
        }
        tableDataPac.setModel(Temp);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmenuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTxtsDent;
    private javax.swing.JPanel PnlTxtsDentDel;
    private javax.swing.JPanel PnlTxtsPac;
    private javax.swing.JPanel PnlTxtsPacDel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelDent;
    private javax.swing.JButton btnDelDentConfirm;
    private javax.swing.JButton btnDelPac;
    private javax.swing.JButton btnDelPacConfirm;
    private javax.swing.JButton btnDent;
    private javax.swing.JButton btnInsertDent;
    private javax.swing.JButton btnInsertPac;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnModDent;
    private javax.swing.JButton btnModPac;
    private javax.swing.JButton btnNewDent;
    private javax.swing.JButton btnNewPac;
    private javax.swing.JButton btnSearchDent;
    private javax.swing.JButton btnSearchPac;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellDent;
    private javax.swing.JLabel lblApellPac;
    private javax.swing.JLabel lblCelDent;
    private javax.swing.JLabel lblDent;
    private javax.swing.JLabel lblDentDel;
    private javax.swing.JLabel lblDentDel1;
    private javax.swing.JLabel lblDentDel3;
    private javax.swing.JLabel lblDentDelNom;
    private javax.swing.JLabel lblDiasDent;
    private javax.swing.JLabel lblEspecDent;
    private javax.swing.JLabel lblEspecPac;
    private javax.swing.JLabel lblIDDent1;
    private javax.swing.JLabel lblIDPacDel;
    private javax.swing.JLabel lblNomApli;
    private javax.swing.JLabel lblNomDent;
    private javax.swing.JLabel lblNomPac;
    private javax.swing.JLabel lblNomTablaDent;
    private javax.swing.JLabel lblNomTablaPac;
    private javax.swing.JLabel lblPac;
    private javax.swing.JLabel lblPacDel;
    private javax.swing.JLabel lblPacDelNom;
    private javax.swing.JLabel lblTelDent;
    private javax.swing.JPanel pnlTableDent;
    private javax.swing.JPanel pnlTablePac;
    private javax.swing.JTable tableDataDent;
    private javax.swing.JTable tableDataPac;
    private javax.swing.JTextField txtApelDent;
    private javax.swing.JTextField txtApelPac;
    private javax.swing.JTextField txtCelDent;
    private javax.swing.JTextField txtDiasDent;
    private javax.swing.JTextField txtEdadPac;
    private javax.swing.JTextField txtEspecDent;
    private javax.swing.JTextField txtNomDent;
    private javax.swing.JTextField txtNomPac;
    private javax.swing.JTextField txtTelDent;
    // End of variables declaration//GEN-END:variables
}
